from pydantic import BaseModel
from datetime import datetime

class SearchHistoryBase(BaseModel):
    """
    Base schema for a search history entry.
    """
    username: str

class SearchHistoryCreate(SearchHistoryBase):
    """
    Schema for creating a new search history entry.
    The frontend will only need to send the username.
    """
    pass

class SearchHistory(SearchHistoryBase):
    """
    Schema for reading a search history entry from the database.
    Includes fields that are auto-generated by the database.
    """
    id: int
    searched_at: datetime

    class Config:
        from_attributes = True